FROM python:3.12
LABEL authors="niki"

ENV PYTHONUNBUFFERED=1

ARG WORKDIR=/wd
ARG USER=user

WORKDIR ${WORKDIR}

RUN useradd --system ${USER} && \
    chown --recursive ${USER} ${WORKDIR}


RUN apt update && apt upgrade --yes

COPY --chown=${USER} requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install --requirement requirements.txt

COPY --chown=${USER} ./app/bot app/bot
USER ${USER}




ENTRYPOINT ["python3", "-m", "app.bot.money_bot"]

