services:
  db:
    image: postgres:latest
    container_name: money_checker
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_money
    ports:
      - "8000:8000"
    env_file:
      - .env.backend
    depends_on:
      - db
    command: bash -c "sleep 2 && alembic upgrade head && uvicorn app.api.main:app --host 0.0.0.0 --port 8000"



  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    env_file:
      - .env.bot
    depends_on:
      - backend



volumes:
  postgres_data:
    driver: local
